const KNOWN_APP_LOGOS: Record<string, string> = {
  'Discord': 'discord.com',
  'Notion': 'notion.so',
  'Figma': 'figma.com',
  'Spotify': 'spotify.com',
  'Slack': 'slack.com',
  'Zoom': 'zoom.us',
  'WhatsApp': 'whatsapp.com',
  'Telegram': 'telegram.org',
  'Signal': 'signal.org',
  'Skype': 'skype.com',
  'Microsoft Teams': 'microsoft.com',
  'Teams': 'microsoft.com',
  'Outlook': 'microsoft.com',
  'Word': 'microsoft.com',
  'Excel': 'microsoft.com',
  'PowerPoint': 'microsoft.com',
  'OneNote': 'microsoft.com',
  'Visual Studio Code': 'code.visualstudio.com',
  'VS Code': 'code.visualstudio.com',
  'Xcode': 'developer.apple.com',
  'Android Studio': 'developer.android.com',
  'Steam': 'store.steampowered.com',
  'Epic Games': 'epicgames.com',
  'Twitch': 'twitch.tv',
  'OBS': 'obsproject.com',
  'OBS Studio': 'obsproject.com',
  'VLC': 'videolan.org',
  'Plex': 'plex.tv',
  '1Password': '1password.com',
  'LastPass': 'lastpass.com',
  'NordVPN': 'nordvpn.com',
  'ExpressVPN': 'expressvpn.com',
  'Dropbox': 'dropbox.com',
  'OneDrive': 'microsoft.com',
  'Google Drive': 'drive.google.com',
  'Webex': 'webex.com',
  'FaceTime': 'apple.com',
  'Messages': 'apple.com',
  'Safari': 'apple.com',
  'Chrome': 'google.com',
  'Firefox': 'mozilla.org',
  'Opera': 'opera.com',
  'Brave': 'brave.com',
  'Arc': 'arc.net',
  'Photoshop': 'adobe.com',
  'Illustrator': 'adobe.com',
  'Premiere': 'adobe.com',
  'After Effects': 'adobe.com',
  'Lightroom': 'adobe.com',
  'Blender': 'blender.org',
  'Unity': 'unity.com',
  'Unreal Engine': 'unrealengine.com',
  'Minecraft': 'minecraft.net',
  'Roblox': 'roblox.com',
  'Fortnite': 'epicgames.com',
  'Valorant': 'playvalorant.com',
  'League of Legends': 'leagueoflegends.com',
  'Coinbase': 'coinbase.com',
  'Binance': 'binance.com',
  'Robinhood': 'robinhood.com',
  'CapCut': 'capcut.com',
  'Loom': 'loom.com',
  'Grammarly': 'grammarly.com',
  'Postman': 'postman.com',
  'Insomnia': 'insomnia.rest',
  'TablePlus': 'tableplus.com',
  'Sequel Pro': 'sequelpro.com',
  'GitHub Desktop': 'github.com',
  'Sourcetree': 'sourcetreeapp.com',
  'iTerm': 'iterm2.com',
  'Terminal': 'apple.com',
  'Alfred': 'alfredapp.com',
  'AutoCAD': 'autodesk.com',
  'Tower': 'git-tower.com',
}

export function getAppLogoUrl(name: string, iconUrl: string | null): string | null {
  if (iconUrl) return iconUrl
  const domain = KNOWN_APP_LOGOS[name]
  return domain ? `https://logo.clearbit.com/${domain}` : null
}
